import { describe, it, expect } from 'vitest'
import { calculateChart } from './calculate'
import {
  interpretChart,
  countElements,
  seasonRelation,
  assessStrength,
} from './interpret'

const bruceLee = calculateChart({
  year: 1940, month: 11, day: 27, hour: 8, minute: 0,
  timeZone: 'America/Los_Angeles', gender: 'male',
})

const ny1990 = calculateChart({
  year: 1990, month: 6, day: 15, hour: 12, minute: 0,
  timeZone: 'America/New_York', gender: 'male',
})

describe('element counting', () => {
  it('counts Bruce Lee’s chart (庚辰 丁亥 甲戌 戊辰): earth-heavy', () => {
    const { counts, total } = countElements(bruceLee)
    expect(total).toBe(8)
    expect(counts).toEqual({ Wood: 1, Fire: 1, Earth: 4, Metal: 1, Water: 1 })
  })

  it('counts the 1990 NY chart (庚午 壬午 辛亥 甲午): no earth at all', () => {
    const { counts, total } = countElements(ny1990)
    expect(total).toBe(8)
    expect(counts).toEqual({ Wood: 1, Fire: 3, Earth: 0, Metal: 2, Water: 2 })
  })

  it('counts six positions when the hour is unknown', () => {
    const chart = calculateChart({
      year: 1990, month: 6, day: 15,
      timeZone: 'America/New_York', gender: 'male',
    })
    expect(countElements(chart).total).toBe(6)
  })
})

describe('season relation', () => {
  it('covers all five relations', () => {
    expect(seasonRelation('Wood', 'Wood')).toBe('same')
    expect(seasonRelation('Wood', 'Water')).toBe('feeds')   // water generates wood
    expect(seasonRelation('Wood', 'Fire')).toBe('drains')   // wood generates fire
    expect(seasonRelation('Metal', 'Fire')).toBe('opposes') // fire controls metal
    expect(seasonRelation('Wood', 'Earth')).toBe('yields')  // wood controls earth
  })
})

describe('strength assessment', () => {
  const even = { Wood: 2, Fire: 2, Earth: 2, Metal: 1, Water: 1 }

  it('many supporters plus a friendly season leans strong', () => {
    const counts = { Wood: 3, Fire: 1, Earth: 1, Metal: 1, Water: 2 }
    expect(assessStrength(counts, 8, 'Wood', 'same').strength).toBe('strong')
  })

  it('few supporters plus an opposing season leans weak', () => {
    const counts = { Wood: 1, Fire: 2, Earth: 2, Metal: 3, Water: 0 }
    expect(assessStrength(counts, 8, 'Wood', 'opposes').strength).toBe('weak')
  })

  it('middling support reads as balanced', () => {
    expect(assessStrength(even, 8, 'Wood', 'yields').strength).toBe('balanced')
  })

  it('supporters = own element plus its resource element', () => {
    // Wood is generated by Water: 2 wood + 1 water = 3 supporters.
    const counts = { Wood: 2, Fire: 2, Earth: 2, Metal: 1, Water: 1 }
    expect(assessStrength(counts, 8, 'Wood', 'yields').supporters).toBe(3)
  })
})

describe('interpretation copy', () => {
  it('calls out a missing element plainly and prominently', () => {
    const reading = interpretChart(ny1990)
    expect(reading.missing).toEqual(['Earth'])
    expect(reading.extreme).toBe(true)
    expect(reading.paragraphs[0]).toContain('There is no earth anywhere in your chart.')
    expect(reading.paragraphs[0]).toContain('The missing element can shape a chart')
  })

  it('reads the 1990 chart as a weak day master (fire season against metal)', () => {
    const reading = interpretChart(ny1990)
    expect(reading.seasonRelation).toBe('opposes')
    expect(reading.strength).toBe('weak')
  })

  it('flags heavy dominance (Bruce Lee’s four earth positions)', () => {
    const reading = interpretChart(bruceLee)
    expect(reading.dominant[0]).toEqual({ element: 'Earth', count: 4 })
    expect(reading.extreme).toBe(true)
    expect(reading.paragraphs[0]).toContain('Earth dominates everything else')
    // The outnumbered day master is stated with concrete numbers.
    expect(reading.paragraphs[0]).toContain(
      'Wood, your day master, holds just 1 of the 8 positions',
    )
  })

  it('frames a weak day master as support, not identity', () => {
    const text = interpretChart(ny1990).paragraphs[1]
    expect(text).toContain('Weak here measures the support you started with')
    expect(text).toContain('you are still the jewel')
  })

  it('avoids chart-as-actor and AI-flavored phrasing', () => {
    // Per tone review: the chart describes circumstances; the person acts.
    // And no stock LLM constructions.
    const banned = [
      'the chart works',
      'charts like this',
      'Middle-weight charts',
      'Add it up',
      "isn't a workaround",
      'not a verdict',
    ]
    for (const chart of [bruceLee, ny1990]) {
      const text = interpretChart(chart).paragraphs.join(' ')
      for (const phrase of banned) {
        expect(text).not.toContain(phrase)
      }
    }
  })

  it('speaks in second person and never in clinical third person', () => {
    for (const chart of [bruceLee, ny1990]) {
      const text = interpretChart(chart).paragraphs.join(' ')
      expect(text).toContain('your')
      expect(text).not.toContain('this person')
      expect(text).not.toContain('the native')
    }
  })

  it('describes an even spread without inventing drama', () => {
    // Scan forward until a chart has all five elements present with none
    // appearing 3+ times, then check that branch of the copy.
    let found = false
    outer: for (let month = 1; month <= 12; month++) {
      for (let day = 1; day <= 28; day += 3) {
        for (const hour of [2, 8, 14, 20]) {
          const chart = calculateChart({
            year: 1975, month, day, hour, minute: 0,
            timeZone: 'Asia/Shanghai', gender: 'female',
          })
          const reading = interpretChart(chart)
          if (reading.missing.length === 0 && reading.dominant.length === 0) {
            expect(reading.extreme).toBe(false)
            expect(reading.paragraphs[0]).toContain('All five elements are present in your chart')
            found = true
            break outer
          }
        }
      }
    }
    expect(found).toBe(true)
  })

  it('adds the soft-edges note only when the hour is unknown', () => {
    const noHour = calculateChart({
      year: 1990, month: 6, day: 15,
      timeZone: 'America/New_York', gender: 'male',
    })
    expect(interpretChart(noHour).paragraphs.join(' ')).toContain('six positions instead of eight')
    expect(interpretChart(ny1990).paragraphs.join(' ')).not.toContain('six positions')
  })
})
