import type { ChartResult } from './calculate'
import type { Element } from './data'

// Rule-based, deterministic interpretation. No model calls: every sentence is
// assembled from the verified chart data, so the free-tier reading can never
// assert something the calculation didn't produce.

export const ELEMENTS: Element[] = ['Wood', 'Fire', 'Earth', 'Metal', 'Water']

/** X generates Y (the productive cycle). */
const GENERATES: Record<Element, Element> = {
  Wood: 'Fire',
  Fire: 'Earth',
  Earth: 'Metal',
  Metal: 'Water',
  Water: 'Wood',
}

/** X controls Y (the controlling cycle). */
const CONTROLS: Record<Element, Element> = {
  Wood: 'Earth',
  Earth: 'Water',
  Water: 'Fire',
  Fire: 'Metal',
  Metal: 'Wood',
}

/** X is generated by Y (the resource element): inverse of GENERATES. */
const GENERATED_BY: Record<Element, Element> = {
  Fire: 'Wood',
  Earth: 'Fire',
  Metal: 'Earth',
  Water: 'Metal',
  Wood: 'Water',
}

/** Traditional imagery for each day master stem, keyed by Chinese character. */
const DAY_MASTER_IMAGERY: Record<string, string> = {
  甲: 'a tall tree — upright, steady growth that does not like being bent',
  乙: 'grass and climbing vines — flexible growth that finds a way around obstacles',
  丙: 'the sun — warmth radiated openly and at scale',
  丁: 'a candle or hearth — contained warmth, focused and close-up',
  戊: 'a mountain — broad, load-bearing, slow to move',
  己: 'garden soil — quiet ground that grows other things',
  庚: 'raw ore and the axe — direct force that cuts first and polishes later',
  辛: 'refined metal and jewelry — precision, edge, and finish',
  壬: 'a river or the sea — momentum that carries things along with it',
  癸: 'rain and mist — subtle water that soaks in everywhere',
}

export type Strength = 'strong' | 'weak' | 'balanced'

export type SeasonRelation =
  | 'same'        // month element matches the day master
  | 'feeds'       // month element generates the day master
  | 'drains'      // day master generates the month element
  | 'opposes'     // month element controls the day master
  | 'yields'      // day master controls the month element

export interface Interpretation {
  counts: Record<Element, number>
  /** number of chart positions counted: 8, or 6 when the hour is unknown */
  total: number
  missing: Element[]
  /** elements appearing in at least 3 positions, strongest first */
  dominant: { element: Element; count: number }[]
  /** true when the balance deserves a prominent callout (a zero or a heavy element) */
  extreme: boolean
  seasonRelation: SeasonRelation
  strength: Strength
  paragraphs: string[]
}

function lower(e: Element): string {
  return e.toLowerCase()
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function countElements(chart: ChartResult): { counts: Record<Element, number>; total: number } {
  const counts: Record<Element, number> = { Wood: 0, Fire: 0, Earth: 0, Metal: 0, Water: 0 }
  const pillars = [chart.yearPillar, chart.monthPillar, chart.dayPillar, chart.hourPillar]
  let total = 0
  for (const p of pillars) {
    if (!p) continue
    counts[p.stem.element]++
    counts[p.branch.element]++
    total += 2
  }
  return { counts, total }
}

export function seasonRelation(dayMaster: Element, monthBranch: Element): SeasonRelation {
  if (monthBranch === dayMaster) return 'same'
  if (GENERATES[monthBranch] === dayMaster) return 'feeds'
  if (GENERATES[dayMaster] === monthBranch) return 'drains'
  if (CONTROLS[monthBranch] === dayMaster) return 'opposes'
  return 'yields'
}

/**
 * First-pass strength read: how many positions match or feed the day master,
 * adjusted by the season (the month branch, weighted because the season sets
 * the climate the whole chart lives in). Deliberately coarse — presented in
 * the copy as a lean, not a verdict.
 */
export function assessStrength(
  counts: Record<Element, number>,
  total: number,
  dayMaster: Element,
  relation: SeasonRelation,
): { strength: Strength; supporters: number } {
  const supporters = counts[dayMaster] + counts[GENERATED_BY[dayMaster]]
  const seasonAdj =
    relation === 'same' ? 1.5 : relation === 'feeds' ? 1 : relation === 'yields' ? 0 : relation === 'drains' ? -0.5 : -1
  const ratio = (supporters + seasonAdj) / total
  const strength: Strength = ratio >= 0.5 ? 'strong' : ratio <= 0.3 ? 'weak' : 'balanced'
  return { strength, supporters }
}

function balanceParagraph(
  counts: Record<Element, number>,
  total: number,
  missing: Element[],
  dominant: { element: Element; count: number }[],
  dayMaster: Element,
): string {
  const sentences: string[] = []
  const heavy = dominant.filter((d) => d.count >= Math.ceil(total / 2))
  const dmOutnumbered =
    counts[dayMaster] <= 1 && dominant.length > 0 && dominant[0].element !== dayMaster

  if (missing.length === 1) {
    sentences.push(`There is no ${lower(missing[0])} anywhere in your chart.`)
  } else if (missing.length > 1) {
    sentences.push(
      `There is no ${missing.map(lower).join(' and no ')} anywhere in your chart.`,
    )
  }

  if (dominant.length > 0) {
    const names = dominant.map((d) => lower(d.element))
    const lead =
      names.length === 1 ? capitalize(names[0]) : capitalize(names.join(' and '))
    const verb = names.length === 1 ? 'dominates' : 'dominate'
    if (dmOutnumbered) {
      sentences.push(
        `${lead} ${verb} everything else, and ${lower(dayMaster)}, your day master, is outnumbered on both sides.`,
      )
    } else {
      sentences.push(`${lead} ${verb} everything else.`)
    }
  } else if (missing.length === 0) {
    const max = Math.max(...ELEMENTS.map((e) => counts[e]))
    const top = ELEMENTS.filter((e) => counts[e] === max)
    sentences.push(
      `All five elements show up in your chart, and none of them runs away with it — ${top
        .map(lower)
        .join(' and ')} sit${top.length === 1 ? 's' : ''} slightly ahead. A spread like this gives you range: no single element holds the wheel, and no door is closed by default.`,
    )
  }

  if (missing.length > 0) {
    sentences.push(
      `The missing element can shape a chart as much as a strong element can. Whether that's working for or against you depends on what's hiding in the branches and the season you were born into.`,
    )
  } else if (heavy.length > 0) {
    sentences.push(
      `That much ${lower(heavy[0].element)} sets the chart's tone: the other elements spend most of their time reacting to it rather than leading.`,
    )
  }

  return sentences.join(' ')
}

function dayMasterParagraph(
  chart: ChartResult,
  relation: SeasonRelation,
  strength: Strength,
  supporters: number,
  total: number,
): string {
  const dm = chart.dayMaster
  const dmName = lower(dm.element)
  const monthName = lower(chart.monthPillar.branch.element)
  const imagery = DAY_MASTER_IMAGERY[dm.chinese]

  const seasonSentence =
    relation === 'same'
      ? `Born in a ${monthName} month, you hold the season — your element is at home in it.`
      : relation === 'feeds'
        ? `Born in a ${monthName} month, the season feeds you: ${monthName} gives rise to ${dmName} in the cycle.`
        : relation === 'drains'
          ? `Born in a ${monthName} month, the season draws on you: ${dmName} spends itself producing ${monthName}.`
          : relation === 'opposes'
            ? `Born in a ${monthName} month, the season pushes against you: ${monthName} keeps ${dmName} in check.`
            : `Born in a ${monthName} month, the season answers to you — ${dmName} controls ${monthName} — though holding that ground takes effort.`

  const strengthSentence =
    strength === 'strong'
      ? `Add it up and your day master leans strong: ${supporters} of your ${total} positions match or feed your element. A strong day master has fuel to spend, and charts like this tend to reward output more than caution.`
      : strength === 'weak'
        ? `Add it up and your day master leans weak: only ${supporters} of your ${total} positions are on your side. That is not a verdict on you — a weak day master reads as someone whose results depend on backing: the right people, the right timing, the right ground. When those line up, the chart works.`
        : `Add it up and your day master sits near the middle: ${supporters} of your ${total} positions support your element. Middle-weight charts move with circumstance — the balance tips one way or the other depending on the years you're moving through.`

  return `You are ${dm.pinyin} — ${dm.polarity.toLowerCase()} ${dmName}, traditionally pictured as ${imagery}. ${seasonSentence} ${strengthSentence}`
}

export function interpretChart(chart: ChartResult): Interpretation {
  const { counts, total } = countElements(chart)
  const missing = ELEMENTS.filter((e) => counts[e] === 0)
  const dominant = ELEMENTS.map((e) => ({ element: e, count: counts[e] }))
    .filter((d) => d.count >= 3)
    .sort((a, b) => b.count - a.count)
  const heavyThreshold = Math.ceil(total / 2)
  const extreme = missing.length > 0 || dominant.some((d) => d.count >= heavyThreshold)

  const relation = seasonRelation(chart.dayMaster.element, chart.monthPillar.branch.element)
  const { strength, supporters } = assessStrength(counts, total, chart.dayMaster.element, relation)

  const paragraphs = [
    balanceParagraph(counts, total, missing, dominant, chart.dayMaster.element),
    dayMasterParagraph(chart, relation, strength, supporters, total),
  ]

  if (!chart.timeKnown) {
    paragraphs.push(
      `Your birth hour is unknown, so this balance reads six positions instead of eight. An hour pillar adds one more stem and one more branch — enough to lift a missing element off zero or tip a close balance — so treat the edges of this reading as soft.`,
    )
  }

  return { counts, total, missing, dominant, extreme, seasonRelation: relation, strength, paragraphs }
}
