import { DateTime, FixedOffsetZone } from 'luxon'
import { Solar } from 'lunar-typescript'
import { STEMS, BRANCHES, type StemInfo, type BranchInfo, type Element } from './data'
import type { BirthInput, ChartResult } from './calculate'

// Luck Pillars (大运): ten-year periods stepping forward or backward from the
// month pillar through the 60-pair cycle.
//
// Verified rules (cross-checked against Wikibooks' Ba Zi guide and multiple
// independent Ba Zi references, Aug 2026):
// - Direction: yang year stem + male, or yin year stem + female → forward;
//   otherwise backward. Year stem is Lichun-exact.
// - Starting age: days from birth to the NEXT jie (forward) or from the
//   PREVIOUS jie back to birth (backward), at 3 days = 1 year (each 2-hour
//   shichen = 10 days). The library implements exactly this (Yun, sect 1).
// - Each period's pillar: month pillar ± n in the sexagenary cycle.
//
// Gui ren (天乙贵人): classic day-stem → branch table, identical across the
// sources checked (甲戊庚→丑未, 乙己→子申, 丙丁→亥酉, 壬癸→卯巳, 辛→午寅).
// School variants exist for this star; we use the most widely cited classic
// version. A period "has gui ren" when its branch is in the day stem's set.

const GUI_REN: Record<string, string[]> = {
  甲: ['丑', '未'],
  戊: ['丑', '未'],
  庚: ['丑', '未'],
  乙: ['子', '申'],
  己: ['子', '申'],
  丙: ['亥', '酉'],
  丁: ['亥', '酉'],
  壬: ['卯', '巳'],
  癸: ['卯', '巳'],
  辛: ['午', '寅'],
}

/** X is generated by Y — the resource element for each element. */
const GENERATED_BY: Record<Element, Element> = {
  Fire: 'Wood',
  Earth: 'Fire',
  Metal: 'Earth',
  Water: 'Metal',
  Wood: 'Water',
}

export type ResourceLevel = 'rich' | 'mixed' | 'scarce'

export interface LuckPeriod {
  /** 1-based decade number */
  index: number
  stem: StemInfo
  branch: BranchInfo
  /** first and last calendar year of the period */
  startYear: number
  endYear: number
  /** age (Western count) at the start of the period */
  startAge: number
  /** how many of the period's two characters supply the day master (0-2) */
  supportCount: number
  resource: ResourceLevel
  guiRen: boolean
}

export interface LuckTimeline {
  forward: boolean
  /** precise start of the first period, counted from birth */
  startAgeYears: number
  startAgeMonths: number
  periods: LuckPeriod[]
  /** index into periods for the period covering today, or -1 if today is before the first */
  currentIndex: number
}

function resourceLevel(count: number): ResourceLevel {
  return count === 2 ? 'rich' : count === 1 ? 'mixed' : 'scarce'
}

/**
 * Compute the luck pillar timeline. Uses the same UTC+8 clock as the year and
 * month pillars, since both the month pillar and the jie boundaries that set
 * the starting age live on that clock.
 */
export function calculateLuck(input: BirthInput, chart: ChartResult): LuckTimeline {
  const hour = input.hour ?? 12
  const minute = input.minute ?? 0
  const wall = DateTime.fromObject(
    { year: input.year, month: input.month, day: input.day, hour, minute },
    { zone: input.timeZone },
  )
  const chinaLocal = wall.setZone(FixedOffsetZone.instance(8 * 60))

  const eightChar = Solar.fromYmdHms(
    chinaLocal.year, chinaLocal.month, chinaLocal.day, chinaLocal.hour, chinaLocal.minute, 0,
  )
    .getLunar()
    .getEightChar()

  const yun = eightChar.getYun(input.gender === 'male' ? 1 : 0)
  const dayMaster = chart.dayMaster.element
  const guiRenBranches = GUI_REN[chart.dayMaster.chinese] ?? []

  const periods: LuckPeriod[] = yun
    .getDaYun(9)
    .slice(1) // index 0 is the pre-luck childhood span, not a pillar
    .map((dy) => {
      const ganzhi = dy.getGanZhi()
      const stem = STEMS[ganzhi[0]]
      const branch = BRANCHES[ganzhi[1]]
      if (!stem || !branch) {
        throw new Error(`Unknown luck pillar: ${ganzhi}`)
      }
      const supportCount =
        (stem.element === dayMaster || stem.element === GENERATED_BY[dayMaster] ? 1 : 0) +
        (branch.element === dayMaster || branch.element === GENERATED_BY[dayMaster] ? 1 : 0)
      return {
        index: dy.getIndex(),
        stem,
        branch,
        startYear: dy.getStartYear(),
        endYear: dy.getEndYear(),
        // Age at the pillar's start: the precise offset from birth (years
        // component) plus a decade per subsequent pillar. Calendar-year
        // subtraction would overcount whenever the pillar starts before the
        // birthday month.
        startAge: yun.getStartYear() + (dy.getIndex() - 1) * 10,
        supportCount,
        resource: resourceLevel(supportCount),
        guiRen: guiRenBranches.includes(ganzhi[1]),
      }
    })

  const nowYear = new Date().getFullYear()
  let currentIndex = -1
  periods.forEach((p, i) => {
    if (nowYear >= p.startYear && nowYear <= p.endYear) currentIndex = i
  })

  return {
    forward: yun.isForward(),
    startAgeYears: yun.getStartYear(),
    startAgeMonths: yun.getStartMonth(),
    periods,
    currentIndex,
  }
}
